server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
      #当前数据源操作类型
      type: com.alibaba.druid.pool.DruidDataSource
      #mysql驱动包
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: renren
      password: 123456
mybatis:
  mapperLocations: classpath:mapper/*.xml
  #所有entity别名类所在包
  type-aliases-package: com.yxm.springcloud.entities