server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态获取路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
#            - After=2020-12-22T20:48:15.333+08:00[Asia/Shanghai] #是中国时区，在到达该时刻之后才能被访问到，否则访问不到。应用场景：定时到某一时刻更新系统。
#            - Before=2020-12-22T21:48:15.333+08:00[Asia/Shanghai] #请求可以在该时间之前访问
#            - Between=2020-12-22T20:48:15.333+08:00[Asia/Shanghai], 2020-12-22T21:48:15.333+08:00[Asia/Shanghai] #请求可以在这两个时间之间访问
#            - Cookie=username, yxm #带cookie的请求，如果不带cookie请求会报404
            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且值为正整数的正则表达式
#            - Host=**.somehost.org,**.anotherhost.org
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
