server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
#      nacos页面查看地址访问localhost:8848
        server-addr: localhost:8848
service-url:
#nacos服务地址http://注册进nacos的服务名
  nacos-user-service: http://nacos-payment-provider